apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: devops-toolkit
  namespace: production
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: db-conn
